### ISSUE TITLE
Data set for Problem 3: Don’t predict, count!

### ISSUE THREAD

**Issue by manashmndl** [chiphuyen/tf-stanford-tutorials#1]
I couldn't find the text data [here](https://cs.fit.edu/~mmahoney/). Could you please provide the url for the data set? Thank you.

**Comment by chiphuyen** [comment]
Sorry I wasn't aware that people posted question here. The full dataset enwki9 can be downloaded here:
http://mattmahoney.net/dc/enwik9

You'll need the perl script at the end of the page http://mattmahoney.net/dc/text.html to preprocess the data. You can just look for "usr/bin/perl".

**Comment by manashmndl** [comment]
Thanks 👍
