### ISSUE TITLE
tensorflow 1.0 support!!

### ISSUE THREAD

**Issue by kashyap32** [chiphuyen/tf-stanford-tutorials#11]

**Comment by chiphuyen** [comment]
I'm teaching the course again next year so I'll update the repo soon to keep it updated.

**Comment by nickai-genious** [comment]
where can i procure the lessons that you speak of?

**Comment by lkhphuc** [comment]
@nickai-genious cs20si.stanford.edu.

**Comment by chiphuyen** [comment]
added TF >1 support
