### ISSUE TITLE
a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by sghaleb1** [chiphuyen/tf-stanford-tutorials#13]
After running `python data.py` I get the following error:

> Preparing raw data into train set and test set ...
> Traceback (most recent call last):
>   File "data.py", line 250, in <module>
>     prepare_raw_data()
>   File "data.py", line 173, in prepare_raw_data
>     id2line = get_lines()
>   File "data.py", line 29, in get_lines
>     parts = line.split(' +++$+++ ')
> TypeError: a bytes-like object is required, not 'str'

**Comment by hdatteln** [comment]
I just ran into the same. 
After casting 'line' (which is data type byte) to string, it runs a bit further:
`parts = str(line).split(' +++$+++ ')`

However, now i am getting this error:

`Traceback (most recent call last):
  File "data.py", line 255, in <module>
    prepare_raw_data()
  File "data.py", line 180, in prepare_raw_data
    questions, answers = question_answers(id2line, convos)
  File "data.py", line 61, in question_answers
    questions.append(id2line[convo[index]])
KeyError: 'L194'
Heidis-MacBook-Pro:c`

**Comment by chiphuyen** [comment]
When opening files, just change all 'rb' and 'wb' to 'r' and 'b'

**Comment by Jayruiping** [comment]
I can not reslove this problem

**Comment by Jayruiping** [comment]
@hdatteln   line 99, in basic_tokenizer     line = re.sub('<u>', '', line)

TypeError: cannot use a string pattern on a bytes-like object

**Comment by Hsy1996** [comment]
@Jayruiping  Hi, have you solved this problem?
