### ISSUE TITLE
[Errno 2] No such file or directory: 'processed/vocab_1000.tsv'

### ISSUE THREAD

**Issue by laubonghaudoi** [chiphuyen/tf-stanford-tutorials#20]
When I ran the `04_word2vec_starter.py` and `04_word2vec_no_frills.py` and `04_word2vec_visualize.py`, functions in the `process_data.py` are called, and occured the following error messages:

> Dataset ready
Traceback (most recent call last):
  File "/home/luffy/Desktop/tf-stanford-tutorials/examples/04_word2vec_visualize.py", line 151, in <modul
e>
    main()
  File "/home/luffy/Desktop/tf-stanford-tutorials/examples/04_word2vec_visualize.py", line 147, in main
    batch_gen = process_data(VOCAB_SIZE, BATCH_SIZE, SKIP_WINDOW)
  File "/home/luffy/Desktop/tf-stanford-tutorials/examples/process_data.py", line 87, in process_data
    dictionary, _ = build_vocab(words, vocab_size)
  File "/home/luffy/Desktop/tf-stanford-tutorials/examples/process_data.py", line 50, in build_vocab
    with open('processed/vocab_1000.tsv', "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'processed/vocab_1000.tsv'

It seems that the text8.zip is successfully downloaded, but where is the ` processed/vocab_1000.tsv` ?

**Comment by emir-munoz** [comment]
`vocab_1000.tsv` file is generated by the `process_data.py` code by processing the `text8.zip` file in these lines https://github.com/chiphuyen/tf-stanford-tutorials/blob/master/examples/process_data.py#L50-L56

The problem you face is that the folder `processed/` does not exist, therefore the file cannot be created. You can add some lines of code to create the folder:
```python
if not os.path.exists(directory):
    os.makedirs(directory)
```
... or create the folder manually.

**Comment by chiphuyen** [comment]
@laubonghaudoi  looks like the problem has been fixed. let me know if you have any other question.
