### ISSUE TITLE
Issue with process_data package 

### ISSUE THREAD

**Issue by shanmukh-t** [chiphuyen/tf-stanford-tutorials#23]
Hi I am going thorough the stanforf-tutorials and trying to run the fourth Task which is 04_word2vec_no_frills but it is asking for Process_data package and I am trying to load it through pip but its showing no such package,later I found there is a python script for process_data.py file and I had ran it, its still showing an error! Any help would appreciated!
Thanks In advance!!!

**Comment by lkhphuc** [comment]
I have the same problem.
At first I want to learn how to input the data to a tensorflow program, but it turns out that this job is a bit complicated for us as lecture 4, so Chip has already written a "process_data" package for us.
However, when I run the word2vec_no_frills, I encountered an error:
`centers, targets = batch_gen.next()
AttributeError: 'generator' object has no attribute 'next'`
As I inspect the code, I also found no "next()" method in the function "get_batch" as well.

Thank you in advance.

**Comment by lkhphuc** [comment]
I found the solution for my problem, turn out that is because of Python2/3 conflict. just change batch_gen.next() to next(batch_gen) and things are fine.

**Comment by shanmukh-t** [comment]
That's good, I have python V 3 installed and I did the same change as you mentioned but still its not working for me.

**Comment by lkhphuc** [comment]
You should first say what is your error, post the error message and your suspicion of where the error is.

**Comment by shanmukh-t** [comment]
OK my bad, the error I am receiving is this "NameError: name 'batch_gen' is not defined", as I am running the Stanford lecture 4 at this point in the code I am facing this issue "centers, targets = next(batch_gen)".

**Comment by lkhphuc** [comment]
Did you use the code provided here in github or you just type in everything from the lecture note? If you only type in the lecture note, you would miss the "main" method, which define variable batch_gen by calling the "process_data" class.
As in here: 
`def main():
    batch_gen = process_data(VOCAB_SIZE, BATCH_SIZE, SKIP_WINDOW)
    word2vec(batch_gen)'

**Comment by shanmukh-t** [comment]
I am using the code provided in github, I had defined the main function but this where it started that saying "ImportError: No module named 'process_data'"  no such module existed.

**Comment by lkhphuc** [comment]
Ahh, then easy, go to the examples, scroll down to find a file named: process_data.py, download it and put it in the same folder with your source code.

**Comment by shanmukh-t** [comment]
Sorry I didn't get it, I had the process_data.py file but should I run that file or what did you mean by keeping it in same folder with the source code??

**Comment by lkhphuc** [comment]
put the process_data.py in the same folder as the source code for lecture 4, in the source code there is already a line call `from process_data import process_data` that import the function to the source code. Just run the entire file and the batch_gen will be created through the imported function `process_data`

**Comment by shanmukh-t** [comment]
Right now I am working on Jupyter notebook and you mean to say that put the process_data.py in my working directory??

**Comment by lkhphuc** [comment]
@shanmukh-t Yes. Just try and run it.

**Comment by chiphuyen** [comment]
@shanmukh-t  Looks like the issue has been resolved. Let me know if you have any question.
