### ISSUE TITLE
Is it Overlap or window-overlap?

### ISSUE THREAD

**Issue by kedartatwawadi** [chiphuyen/tf-stanford-tutorials#3]
Hello Chip,

I am a Stanford student following your class. Thanks a lot for the amazing sample code gists which are very useful. I had a small suggestion in [11_char_rnn_gist.py]( tf-stanford-tutorials/examples/11_char_rnn_gist.py ) at Line 32. I believe, ` for start in range(0, len(text) - window, overlap):` the overlap should be (window-overlap)?

**Comment by chiphuyen** [comment]
thanks. you can call it what you want, but keep in mind that this is different from the window model.
