### ISSUE TITLE
 03_logistic_regression_mnist_sol.py

### ISSUE THREAD

**Issue by aysegulucar2016** [chiphuyen/tf-stanford-tutorials#39]
H,

I type  "python 03_logistic_regression_mnist_sol.py"
the error is
File "03_logistic_regression_mnist_sol.py", line 87, in <module>
    total_correct_preds += accuracy_batch
TypeError: unsupported operand type(s) for +=: 'int' and 'list'

what is problem?

Thanks

**Comment by LujunWeng** [comment]
Remove the brackets around `accuracy`
`accuracy_batch = sess.run([accuracy], feed_dict={X: X_batch, Y:Y_batch}) `

**Comment by aysegulucar2016** [comment]
Total time: 20.569292783737183 seconds
Optimization Finished!
Accuracy 0.9143

It was solved. Thanks
