### ISSUE TITLE
lack of definition of CONTENT_WEIGHT, STYLE_WEIGHT(in style_transfer_sols.py), prev_layer_name (in vgg_model_sols.py)

### ISSUE THREAD

**Issue by tcglarry** [chiphuyen/tf-stanford-tutorials#4]
HI, Tks for the post, very helpful.

As title, I found several variable undefined, 

for prev_layer_name, I think, it should be prev_name.name, however ':' is not accepted as scope name. So I changed ':' to '_', and it works 

For CONTENT_WEIGHT and STYLE_WEIGHT, how to define it ?
(of course, omitted the weight could let the program keep running)
Tks 
Larry

**Comment by chiphuyen** [comment]
you're right. i've added content_weight and style_weight. you don't need prev_layer_name
