### ISSUE TITLE
can you also upload processed/vocab_1000.tsv ?

### ISSUE THREAD

**Issue by shaoweipng** [chiphuyen/tf-stanford-tutorials#9]
I notice this file is missing?

thanks

**Comment by shaoweipng** [comment]
nvm, i read the source code again, and realized what's missing is a processed directory. thanks!

**Comment by Alexkevin** [comment]
can i ask what is missing? I'm still in trouble with it

**Comment by shaoweipng** [comment]
@Alexkevin: in the repo,
mkdir processed
that should fix it
